import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    appTitle: "MyDigital ID Helper",
    registerTitle: "Register New Account",
    registerDesc: "Register a new ID",
    loginTitle: "Login",
    loginDesc: "Access existing account",
    scanIC: "Scan IC",
    takePhoto: "Take Photo",
    processing: "Processing...",
    icNumber: "IC Number",
    fullName: "Full Name",
    next: "Next",
    back: "Back",
    scanFace: "Scan Face",
    recordVoice: "Record Voice",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    registerSuccess: "Registration Successful",
    faceMatchSuccess: "Face Matched Successfully",
    faceMatchFailed: "Face Match Failed",
    rescan: "Rescan",
    voicePrompt: "Please read: \"My name is {name} and I want to register.\"",
    voiceRecorded: "Voice Recorded Successfully",
    goToLogin: "Go to Login",
    confirmation: "Confirmation",
    enterIC: "Enter IC Number",
    check: "Check",
    notRegistered: "You are not registered. Please go back to register.",
    welcomeBack: "Welcome back, {name}",
    selectMethod: "Select Verification Method",
    faceAuth: "Face Verification",
    voiceAuth: "Voice Verification",
    loginVoicePrompt: "My name is {name}, I want to access my account",
    loginSuccess: "Login Successful",
    goHome: "Go to Home",
    goMain: "Go to Main",
    signOut: "Sign Out",
    pressToTalk: "Press to talk, release to stop",
    listening: "Listening...",
    sara: "SUMBANGAN ASAS RAHMAH (SARA)",
    str: "STR",
    mainWelcome: "Hello! How can I help you today?",
    enrolled: "Enrolled",
    notEnrolled: "Not Enrolled",
    loadingData: "Loading...",
    monthlyBenefit: "Monthly Benefit",
    nextPayment: "Next Payment",
    oneOffBalance: "One-Off",
    regularBalance: "Regular",
    totalStores: "Total Stores",
    strNotEnrolledMsg: "You are not enrolled in STR. Tap to check eligibility.",
    saraNotEnrolledMsg: "You are not enrolled in SARA. Tap to learn more.",
    tapToViewMore: "Tap to view more",
    quickOverview: "Quick Overview",
    eligibleForStr: "Eligible for STR",
    applicationApproved: "Your application has been approved.",
    upcomingPayments: "Upcoming Payments",
    recentPayment: "Recent Payment",
    expected: "Expected",
    completed: "Completed",
    saraBalance: "SARA Balance",
    oneOff: "One-off",
    payNow: "Pay Now",
    lastTransaction: "Last",
    nearbyStores: "Nearby SARA Stores",
    showMap: "Show Map",
    hideMap: "Hide Map",
    distance: "Distance",
    notEligibleStr: "Not Eligible for STR",
    notEligibleMsg: "You are not currently eligible for the STR program.",
    bsnBranches: "Nearest BSN Branches",
    visitBranch: "Visit a branch to learn more about STR eligibility.",
    newApplication: "New Application",
    carriesForward: "Carries Forward (No Expiry)",
    upcomingSaraPayment: "Upcoming SARA Payment",
    payWithSara: "Pay with SARA",
    upcomingReminders: "Upcoming Reminders",
    noReminders: "No reminders at this time",
    viewAllReminders: "View All Reminders",
    today: "Today",
    tomorrow: "Tomorrow",
    overdue: "Overdue",
    in: "In",
    days: "days",
    generateQR: "Generate QR Code",
    saraPaymentQR: "SARA Payment QR Code",
    scanToPayWithSARA: "Scan to Pay with SARA",
    qrInstruction1: "Show this QR code at any SARA merchant",
    qrInstruction2: "Merchant will scan to process payment",
    qrInstruction3: "Payment will be deducted from your SARA balance",
    transactionID: "Transaction ID",
    validFor: "Valid For",
    expiringSoon: "Expiring Soon",
    minutesRemaining: "minutes remaining",
    expiresIn15Mins: "15 minutes",
    download: "Download",
    share: "Share",
    generatingQR: "Generating QR Code...",
    qrGenerationFailed: "Failed to generate QR code",
    tryAgain: "Try Again",
    qrCodeCopied: "QR code copied to clipboard",
    secondsRemaining: "seconds remaining",
    refresh: "Refresh",
  },
  ms: {
    appTitle: "Pembantu ID Digital Saya",
    registerTitle: "Daftar Akaun Baru",
    registerDesc: "Daftar ID baru",
    loginTitle: "Log Masuk",
    loginDesc: "Akses akaun sedia ada",
    scanIC: "Imbas IC",
    takePhoto: "Ambil Gambar",
    processing: "Sedang Memproses...",
    icNumber: "Nombor IC",
    fullName: "Nama Penuh",
    next: "Seterusnya",
    back: "Kembali",
    scanFace: "Imbas Wajah",
    recordVoice: "Rakaman Suara",
    startRecording: "Mula Merakam",
    stopRecording: "Berhenti Merakam",
    registerSuccess: "Pendaftaran Berjaya",
    faceMatchSuccess: "Wajah Berjaya Dipadankan",
    faceMatchFailed: "Padanan Wajah Gagal",
    rescan: "Imbas Semula",
    voicePrompt: "Sila baca: \"Nama saya {name} dan saya ingin mendaftar.\"",
    voiceRecorded: "Suara Berjaya Dirakam",
    goToLogin: "Pergi ke Log Masuk",
    confirmation: "Pengesahan",
    enterIC: "Masukkan Nombor IC",
    check: "Semak",
    notRegistered: "Anda belum mendaftar. Sila kembali untuk mendaftar.",
    welcomeBack: "Selamat kembali, {name}",
    selectMethod: "Pilih Kaedah Pengesahan",
    faceAuth: "Pengesahan Wajah",
    voiceAuth: "Pengesahan Suara",
    loginVoicePrompt: "Nama saya {name}, saya ingin mengakses akaun saya",
    loginSuccess: "Log Masuk Berjaya",
    goHome: "Pergi ke Laman Utama",
    goMain: "Pergi ke Halaman Utama",
    signOut: "Log Keluar",
    pressToTalk: "Tekan untuk bercakap, lepas untuk berhenti",
    listening: "Sedang mendengar...",
    sara: "SUMBANGAN ASAS RAHMAH (SARA)",
    str: "STR",
    mainWelcome: "Helo! Bagaimana saya boleh membantu anda hari ini?",
    enrolled: "Terdaftar",
    notEnrolled: "Tidak Terdaftar",
    loadingData: "Memuatkan...",
    monthlyBenefit: "Bantuan Bulanan",
    nextPayment: "Pembayaran Seterusnya",
    oneOffBalance: "Sekali Sahaja",
    regularBalance: "Tetap",
    totalStores: "Jumlah Kedai",
    strNotEnrolledMsg: "Anda tidak berdaftar dalam STR. Ketik untuk semak kelayakan.",
    saraNotEnrolledMsg: "Anda tidak berdaftar dalam SARA. Ketik untuk ketahui lebih lanjut.",
    tapToViewMore: "Ketik untuk lihat lebih",
    quickOverview: "Ringkasan Pantas",
    eligibleForStr: "Layak untuk STR",
    applicationApproved: "Permohonan anda telah diluluskan.",
    upcomingPayments: "Pembayaran Akan Datang",
    recentPayment: "Pembayaran Terkini",
    expected: "Dijangka",
    completed: "Selesai",
    saraBalance: "Baki SARA",
    oneOff: "Sekali Sahaja",
    payNow: "Bayar Sekarang",
    lastTransaction: "Terakhir",
    nearbyStores: "Kedai SARA Berdekatan",
    showMap: "Tunjuk Peta",
    hideMap: "Sembunyikan Peta",
    distance: "Jarak",
    notEligibleStr: "Tidak Layak untuk STR",
    notEligibleMsg: "Anda tidak layak untuk program STR pada masa ini.",
    bsnBranches: "Cawangan BSN Terdekat",
    visitBranch: "Lawati cawangan untuk ketahui lebih lanjut tentang kelayakan STR.",
    newApplication: "Permohonan Baru",
    carriesForward: "Bawa Ke Hadapan (Tiada Tamat Tempoh)",
    upcomingSaraPayment: "Pembayaran SARA Akan Datang",
    payWithSara: "Bayar dengan SARA",
    upcomingReminders: "Peringatan Akan Datang",
    noReminders: "Tiada peringatan pada masa ini",
    viewAllReminders: "Lihat Semua Peringatan",
    today: "Hari Ini",
    tomorrow: "Esok",
    overdue: "Tertunggak",
    in: "Dalam",
    days: "hari",
    generateQR: "Jana Kod QR",
    saraPaymentQR: "Kod QR Pembayaran SARA",
    scanToPayWithSARA: "Imbas untuk Bayar dengan SARA",
    qrInstruction1: "Tunjukkan kod QR ini di mana-mana kedai SARA",
    qrInstruction2: "Peniaga akan mengimbas untuk memproses pembayaran",
    qrInstruction3: "Pembayaran akan ditolak dari baki SARA anda",
    transactionID: "ID Transaksi",
    validFor: "Sah Untuk",
    expiringSoon: "Akan Tamat Tempoh",
    minutesRemaining: "minit lagi",
    expiresIn15Mins: "15 minit",
    download: "Muat Turun",
    share: "Kongsi",
    generatingQR: "Menjana Kod QR...",
    qrGenerationFailed: "Gagal menjana kod QR",
    tryAgain: "Cuba Lagi",
    qrCodeCopied: "Kod QR disalin ke papan keratan",
    secondsRemaining: "saat lagi",
    refresh: "Muat Semula",
  },
  'zh-cn': {
    appTitle: "我的网络电子身份助手",
    registerTitle: "注册新账户",
    registerDesc: "注册新ID",
    loginTitle: "登录",
    loginDesc: "访问现有账户",
    scanIC: "扫描身份证",
    takePhoto: "拍照",
    processing: "处理中...",
    icNumber: "身份证号码",
    fullName: "全名",
    next: "下一步",
    back: "返回",
    scanFace: "扫描人脸",
    recordVoice: "录制语音",
    startRecording: "开始录音",
    stopRecording: "停止录音",
    registerSuccess: "注册成功",
    faceMatchSuccess: "人脸匹配成功",
    faceMatchFailed: "人脸匹配失败",
    rescan: "重新扫描",
    voicePrompt: "请朗读：“我的名字是 {name}，我想注册。”",
    voiceRecorded: "语音录制成功",
    goToLogin: "前往登录",
    confirmation: "确认",
    enterIC: "输入身份证号码",
    check: "检查",
    notRegistered: "您尚未注册。请返回注册。",
    welcomeBack: "欢迎回来，{name}",
    selectMethod: "选择验证方式",
    faceAuth: "人脸验证",
    voiceAuth: "语音验证",
    loginVoicePrompt: "我的名字是 {name}，我想访问我的账户",
    loginSuccess: "登录成功",
    goHome: "前往主页",
    goMain: "前往主页面",
    signOut: "登出",
    pressToTalk: "按住说话，松开停止",
    listening: "正在聆听...",
    sara: "SUMBANGAN ASAS RAHMAH (SARA)",
    str: "STR",
    mainWelcome: "你好！今天有什么可以帮您的吗？",
    enrolled: "已注册",
    notEnrolled: "未注册",
    loadingData: "加载中...",
    monthlyBenefit: "每月津贴",
    nextPayment: "下次付款",
    oneOffBalance: "一次性",
    regularBalance: "定期",
    totalStores: "商店总数",
    strNotEnrolledMsg: "您尚未注册STR。点击查看资格。",
    saraNotEnrolledMsg: "您尚未注册SARA。点击了解更多。",
    tapToViewMore: "点击查看更多",
    quickOverview: "快速概览",
    eligibleForStr: "符合STR资格",
    applicationApproved: "您的申请已获批准。",
    upcomingPayments: "即将到来的付款",
    recentPayment: "最近付款",
    expected: "预计",
    completed: "已完成",
    saraBalance: "SARA余额",
    oneOff: "一次性",
    payNow: "立即支付",
    lastTransaction: "最后",
    nearbyStores: "附近的SARA商店",
    showMap: "显示地图",
    hideMap: "隐藏地图",
    distance: "距离",
    notEligibleStr: "不符合STR资格",
    notEligibleMsg: "您目前不符合STR计划的资格。",
    bsnBranches: "最近的BSN分行",
    visitBranch: "访问分行以了解更多关于STR资格的信息。",
    newApplication: "新申请",
    carriesForward: "Carries Forward (No Expiry)",
    upcomingSaraPayment: "Upcoming SARA Payment",
    payWithSara: "Pay with SARA",
    upcomingReminders: "即将到来的提醒",
    noReminders: "目前没有提醒",
    viewAllReminders: "查看所有提醒",
    today: "今天",
    tomorrow: "明天",
    overdue: "逾期",
    in: "在",
    days: "天",
    generateQR: "生成二维码",
    saraPaymentQR: "SARA 付款二维码",
    scanToPayWithSARA: "扫描使用 SARA 付款",
    qrInstruction1: "在任何 SARA 商家出示此二维码",
    qrInstruction2: "商家将扫描以处理付款",
    qrInstruction3: "付款将从您的 SARA 余额中扣除",
    transactionID: "交易编号",
    validFor: "有效期",
    expiringSoon: "即将过期",
    minutesRemaining: "分钟剩余",
    expiresIn15Mins: "15 分钟",
    download: "下载",
    share: "分享",
    generatingQR: "正在生成二维码...",
    qrGenerationFailed: "生成二维码失败",
    tryAgain: "重试",
    qrCodeCopied: "二维码已复制到剪贴板",
    secondsRemaining: "秒剩余",
    refresh: "刷新",
  },
  'zh-tw': {
    appTitle: "我的網絡電子身份助手",
    registerTitle: "註冊新賬戶",
    registerDesc: "註冊新ID",
    loginTitle: "登錄",
    loginDesc: "訪問現有賬戶",
    scanIC: "掃描身份證",
    takePhoto: "拍照",
    processing: "處理中...",
    icNumber: "身份證號碼",
    fullName: "全名",
    next: "下一步",
    back: "返回",
    scanFace: "掃描人臉",
    recordVoice: "錄製語音",
    startRecording: "開始錄音",
    stopRecording: "停止錄音",
    registerSuccess: "註冊成功",
    faceMatchSuccess: "人臉匹配成功",
    faceMatchFailed: "人臉匹配失敗",
    rescan: "重新掃描",
    voicePrompt: "請朗讀：“我的名字是 {name}，我想註冊。”",
    voiceRecorded: "語音錄製成功",
    goToLogin: "前往登錄",
    confirmation: "確認",
    enterIC: "輸入身份證號碼",
    check: "檢查",
    notRegistered: "您尚未註冊。請返回註冊。",
    welcomeBack: "歡迎回來，{name}",
    selectMethod: "選擇驗證方式",
    faceAuth: "人臉驗證",
    voiceAuth: "語音驗證",
    loginVoicePrompt: "我的名字是 {name}，我想訪問我的賬戶",
    loginSuccess: "登錄成功",
    goHome: "前往主頁",
    goMain: "前往主頁面",
    signOut: "登出",
    pressToTalk: "按住說話，鬆開結束",
    listening: "正在聆聽...",
    myKasih: "MyKasih / SARA",
    str: "STR",
    mainWelcome: "你好！今天有什麼可以幫您的嗎？",
  },
  ta: {
    appTitle: "எனது டிஜிட்டல் அடையாள உதவியாளர்",
    registerTitle: "புதிய கணக்கை பதிவு செய்யவும்",
    registerDesc: "புதிய அடையாளத்தை பதிவு செய்யவும்",
    loginTitle: "உள்நுழைய",
    loginDesc: "தற்போதைய கணக்கை அணுகவும்",
    scanIC: "IC ஸ்கேன்",
    takePhoto: "புகைப்படம் எடு",
    processing: "செயலாக்குகிறது...",
    icNumber: "IC எண்",
    fullName: "முழு பெயர்",
    next: "அடுத்தது",
    back: "பின்னால்",
    scanFace: "முகம் ஸ்கேன்",
    recordVoice: "குரல் பதிவு",
    startRecording: "பதிவைத் தொடங்கு",
    stopRecording: "பதிவை நிறுத்து",
    registerSuccess: "பதிவு வெற்றிகரமாக முடிந்தது",
    faceMatchSuccess: "முகம் வெற்றிகரமாக பொருந்தியது",
    faceMatchFailed: "முகம் பொருந்தவில்லை",
    rescan: "மீண்டும் ஸ்கேன் செய்",
    voicePrompt: "தயவுசெய்து படிக்கவும்: \"என் பெயர் {name} மற்றும் நான் பதிவு செய்ய விரும்புகிறேன்.\"",
    voiceRecorded: "குரல் வெற்றிகரமாக பதிவு செய்யப்பட்டது",
    goToLogin: "உள்நுழையச் செல்லவும்",
    confirmation: "உறுதிப்படுத்தல்",
    enterIC: "IC எண்ணை உள்ளிடவும்",
    check: "சரிபார்க்கவும்",
    notRegistered: "நீங்கள் பதிவு செய்யவில்லை. பதிவு செய்ய மீண்டும் செல்லவும்.",
    welcomeBack: "மீண்டும் வருக, {name}",
    selectMethod: "சரிபார்ப்பு முறையைத் தேர்ந்தெடுக்கவும்",
    faceAuth: "முகம் சரிபார்ப்பு",
    voiceAuth: "குரல் சரிபார்ப்பு",
    loginVoicePrompt: "என் பெயர் {name}, நான் எனது கணக்கை அணுக விரும்புகிறேன்",
    loginSuccess: "உள்நுழைவு வெற்றிகரமாக முடிந்தது",
    goHome: "முகப்புக்குச் செல்லவும்",
    goMain: "முக்கிய பக்கத்திற்குச் செல்லவும்",
    signOut: "வெளியேறு",
    pressToTalk: "பேச அழுத்தவும், நிறுத்த விடுங்கள்",
    listening: "கேட்கிறது...",
    sara: "SUMBANGAN ASAS RAHMAH (SARA)",
    str: "STR",
    mainWelcome: "வணக்கம்! இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    enrolled: "பதிவு செய்யப்பட்டது",
    notEnrolled: "பதிவு செய்யப்படவில்லை",
    loadingData: "ஏற்றுகிறது...",
    monthlyBenefit: "மாதாந்திர உதவி",
    nextPayment: "அடுத்த கொடுப்பனவு",
    oneOffBalance: "ஒருமுறை",
    regularBalance: "வழக்கமான",
    totalStores: "மொத்த கடைகள்",
    strNotEnrolledMsg: "நீங்கள் STR இல் பதிவு செய்யப்படவில்லை. தகுதியை சரிபார்க்க தட்டவும்.",
    saraNotEnrolledMsg: "நீங்கள் SARA இல் பதிவு செய்யப்படவில்லை. மேலும் அறிய தட்டவும்.",
    tapToViewMore: "மேலும் பார்க்க தட்டவும்",
    quickOverview: "விரைவு மேலோட்டம்",
    eligibleForStr: "STR தகுதியுடையவர்",
    applicationApproved: "உங்கள் விண்ணப்பம் அங்கீகரிக்கப்பட்டது.",
    upcomingPayments: "வரவிருக்கும் கொடுப்பனவுகள்",
    recentPayment: "சமீபத்திய கொடுப்பனவு",
    expected: "எதிர்பார்க்கப்படுகிறது",
    completed: "முடிந்தது",
    saraBalance: "SARA இருப்பு",
    oneOff: "ஒருமுறை",
    payNow: "இப்போது செலுத்தவும்",
    lastTransaction: "கடைசி",
    nearbyStores: "அருகிலுள்ள SARA கடைகள்",
    showMap: "வரைபடத்தைக் காட்டு",
    hideMap: "வரைபடத்தை மறை",
    distance: "தூரம்",
    notEligibleStr: "STR க்கு தகுதியற்றவர்",
    notEligibleMsg: "நீங்கள் தற்போது STR திட்டத்திற்கு தகுதியற்றவர்.",
    bsnBranches: "அருகிலுள்ள BSN கிளைகள்",
    visitBranch: "STR தகுதி பற்றி மேலும் அறிய கிளையைப் பார்வையிடவும்.",
    newApplication: "புதிய விண்ணப்பம்",
    carriesForward: "முன்னோக்கி கொண்டு செல்லப்படும் (காலாவதி இல்லை)",
    upcomingSaraPayment: "வரவிருக்கும் SARA கொடுப்பனவு",
    payWithSara: "SARA மூலம் செலுத்தவும்",
    upcomingReminders: "வரவிருக்கும் நினைவூட்டல்கள்",
    noReminders: "இந்த நேரத்தில் நினைவூட்டல்கள் இல்லை",
    viewAllReminders: "அனைத்து நினைவூட்டல்களையும் பார்க்கவும்",
    today: "இன்று",
    tomorrow: "நாளை",
    overdue: "காலதாமதமானது",
    in: "இல்",
    days: "நாட்கள்",
    generateQR: "QR குறியீடு உருவாக்கு",
    saraPaymentQR: "SARA கட்டண QR குறியீடு",
    scanToPayWithSARA: "SARA மூலம் பணம் செலுத்த ஸ்கேன் செய்யவும்",
    qrInstruction1: "இந்த QR குறியீட்டை எந்த SARA வணிகரிடமும் காட்டவும்",
    qrInstruction2: "வணிகர் கட்டணத்தை செயல்படுத்த ஸ்கேன் செய்வார்",
    qrInstruction3: "கட்டணம் உங்கள் SARA இருப்பிலிருந்து கழிக்கப்படும்",
    transactionID: "பரிவர்த்தனை ஐடி",
    validFor: "செல்லுபடியாகும் காலம்",
    expiringSoon: "விரைவில் காலாவதியாகும்",
    minutesRemaining: "நிமிடங்கள் மீதம்",
    expiresIn15Mins: "15 நிமிடங்கள்",
    download: "பதிவிறக்கு",
    share: "பகிர்",
    generatingQR: "QR குறியீடு உருவாக்கப்படுகிறது...",
    qrGenerationFailed: "QR குறியீடு உருவாக்க முடியவில்லை",
    tryAgain: "மீண்டும் முயற்சிக்கவும்",
    qrCodeCopied: "QR குறியீடு கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது",
    secondsRemaining: "விநாடிகள் மீதம்",
    refresh: "புதுப்பிக்கவும்",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [currentLanguage, setCurrentLanguage] = useState('en'); // Alias for consistency

  // Sync both states
  const changeLanguage = (lang) => {
    setLanguage(lang);
    setCurrentLanguage(lang);
  };

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      currentLanguage, 
      setLanguage: changeLanguage, 
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
