import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    appTitle: "MyDigital ID Helper",
    registerTitle: "Register New Account",
    registerDesc: "Register a new ID",
    loginTitle: "Login",
    loginDesc: "Access existing account",
    scanIC: "Scan IC",
    takePhoto: "Take Photo",
    processing: "Processing...",
    icNumber: "IC Number",
    fullName: "Full Name",
    next: "Next",
    back: "Back",
    scanFace: "Scan Face",
    recordVoice: "Record Voice",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    registerSuccess: "Registration Successful",
    faceMatchSuccess: "Face Matched Successfully",
    faceMatchFailed: "Face Match Failed",
    rescan: "Rescan",
    voicePrompt: "Please read: \"My name is {name} and I want to register.\"",
    voiceRecorded: "Voice Recorded Successfully",
    goToLogin: "Go to Login",
    confirmation: "Confirmation",
    enterIC: "Enter IC Number",
    check: "Check",
    notRegistered: "You are not registered. Please go back to register.",
    welcomeBack: "Welcome back, {name}",
    selectMethod: "Select Verification Method",
    faceAuth: "Face Verification",
    voiceAuth: "Voice Verification",
    loginVoicePrompt: "My name is {name}, I want to access my account",
    loginSuccess: "Login Successful",
    goHome: "Go to Home",
    goMain: "Go to Main",
    signOut: "Sign Out",
    pressToTalk: "Press to talk, release to stop",
    listening: "Listening...",
    myKasih: "MyKasih / SARA",
    str: "STR",
    mainWelcome: "Hello! How can I help you today?",
    
    // Family Dock
    myFamily: "My Family",
    noFamilyMembers: "No family members added yet.",
    pendingRequests: "PENDING REQUESTS",
    wantsToAdd: "wants to add you.",
    accept: "Accept",
    reject: "Reject",
    requestSent: "Request sent",
    alreadySent: "Request already sent.",
    alreadyMember: "This user is already in your family list.",
    
    // MyKasih Page
    myKasihBalance: "MyKasih Balance",
    saraBalance: "SARA Balance",
    expires: "Expires",
    lastTransaction: "Last",
    payNow: "Pay Now",
    payWithSara: "Pay with SARA",
    carriesForward: "Carries Forward (No Expiry)",
    upcomingSara: "Upcoming SARA Payment",
    nearbyMerchants: "Nearby MyKasih Merchants",
    interactiveMap: "Interactive Map View",
    away: "away",
    navigate: "Navigate",
    scanToPay: "Scan to Pay",
    scanInstruction: "Show this QR code to the cashier to use your MyKasih balance.",
    limitNote: "Max transaction limit: RM100",
    close: "Close",
    
    // STR Page
    eligibleStr: "Eligible for STR",
    applicationApproved: "Your application has been approved.",
    upcomingPayments: "Upcoming Payments",
    expected: "Expected",
    recentPayment: "Recent Payment",
    date: "Date",
    notEligible: "Not Eligible",
    notEligibleDesc: "You are currently not registered or eligible for STR.",
    nearestBsn: "Nearest BSN Branches",
    howToRegister: "How to Register",
    registerInstruction: "You can register for STR through the official MySTR portal.",
    goToPortal: "Go to MySTR Portal",
    depositedStatus: "Deposited money into your account",
    
    // AI Responses
    aiCheckStr: "You can check your STR status by clicking the button on the right.",
    aiHelp: "I am here to help. Press the button to ask about MyKasih or STR.",
    aiRegistered: "You are already registered and logged in.",
    aiDefault: "I heard you say: \"{text}\". How can I help you with MyKasih or STR?",
  },
  ms: {
    appTitle: "Pembantu ID Digital Saya",
    registerTitle: "Daftar Akaun Baru",
    registerDesc: "Daftar ID baru",
    loginTitle: "Log Masuk",
    loginDesc: "Akses akaun sedia ada",
    scanIC: "Imbas IC",
    takePhoto: "Ambil Gambar",
    processing: "Sedang Memproses...",
    icNumber: "Nombor IC",
    fullName: "Nama Penuh",
    next: "Seterusnya",
    back: "Kembali",
    scanFace: "Imbas Wajah",
    recordVoice: "Rakaman Suara",
    startRecording: "Mula Merakam",
    stopRecording: "Berhenti Merakam",
    registerSuccess: "Pendaftaran Berjaya",
    faceMatchSuccess: "Wajah Berjaya Dipadankan",
    faceMatchFailed: "Padanan Wajah Gagal",
    rescan: "Imbas Semula",
    voicePrompt: "Sila baca: \"Nama saya {name} dan saya ingin mendaftar.\"",
    voiceRecorded: "Suara Berjaya Dirakam",
    goToLogin: "Pergi ke Log Masuk",
    confirmation: "Pengesahan",
    enterIC: "Masukkan Nombor IC",
    check: "Semak",
    notRegistered: "Anda belum mendaftar. Sila kembali untuk mendaftar.",
    welcomeBack: "Selamat kembali, {name}",
    selectMethod: "Pilih Kaedah Pengesahan",
    faceAuth: "Pengesahan Wajah",
    voiceAuth: "Pengesahan Suara",
    loginVoicePrompt: "Nama saya {name}, saya ingin mengakses akaun saya",
    loginSuccess: "Log Masuk Berjaya",
    goHome: "Pergi ke Laman Utama",
    goMain: "Pergi ke Halaman Utama",
    signOut: "Log Keluar",
    pressToTalk: "Tekan untuk bercakap, lepas untuk berhenti",
    listening: "Sedang mendengar...",
    myKasih: "MyKasih / SARA",
    str: "STR",
    mainWelcome: "Helo! Bagaimana saya boleh membantu anda hari ini?",

    // Family Dock
    myFamily: "Keluarga Saya",
    noFamilyMembers: "Tiada ahli keluarga ditambah lagi.",
    pendingRequests: "PERMINTAAN TERTUNGGAK",
    wantsToAdd: "ingin menambah anda.",
    accept: "Terima",
    reject: "Tolak",
    requestSent: "Permintaan dihantar",
    alreadySent: "Permintaan sudah dihantar.",
    alreadyMember: "Pengguna ini sudah ada dalam senarai keluarga anda.",
    
    // MyKasih Page
    myKasihBalance: "Baki MyKasih",
    saraBalance: "Baki SARA",
    expires: "Tamat Tempoh",
    lastTransaction: "Terakhir",
    payNow: "Bayar Sekarang",
    payWithSara: "Bayar dengan SARA",
    carriesForward: "Bawa Ke Hadapan (Tiada Tamat Tempoh)",
    upcomingSara: "Bayaran SARA Akan Datang",
    nearbyMerchants: "Pedagang MyKasih Berdekatan",
    interactiveMap: "Paparan Peta Interaktif",
    away: "jauh",
    navigate: "Navigasi",
    scanToPay: "Imbas untuk Bayar",
    scanInstruction: "Tunjukkan kod QR ini kepada juruwang untuk menggunakan baki MyKasih anda.",
    limitNote: "Had transaksi maksimum: RM100",
    close: "Tutup",
    
    // STR Page
    eligibleStr: "Layak untuk STR",
    applicationApproved: "Permohonan anda telah diluluskan.",
    upcomingPayments: "Bayaran Akan Datang",
    expected: "Jangkaan",
    recentPayment: "Bayaran Terkini",
    date: "Tarikh",
    notEligible: "Tidak Layak",
    notEligibleDesc: "Anda kini tidak berdaftar atau tidak layak untuk STR.",
    nearestBsn: "Cawangan BSN Terdekat",
    howToRegister: "Cara Mendaftar",
    registerInstruction: "Anda boleh mendaftar untuk STR melalui portal rasmi MySTR.",
    goToPortal: "Pergi ke Portal MySTR",
    depositedStatus: "Wang telah dikreditkan ke akaun anda",

    // AI Responses
    aiCheckStr: "Anda boleh menyemak status STR anda dengan menekan butang di sebelah kanan.",
    aiHelp: "Saya di sini untuk membantu. Tekan butang untuk bertanya tentang MyKasih atau STR.",
    aiRegistered: "Anda sudah berdaftar dan log masuk.",
    aiDefault: "Saya dengar anda berkata: \"{text}\". Bagaimana saya boleh membantu anda dengan MyKasih atau STR?",
  },
  'zh-cn': {
    appTitle: "我的网络电子身份助手",
    registerTitle: "注册新账户",
    registerDesc: "注册新ID",
    loginTitle: "登录",
    loginDesc: "访问现有账户",
    scanIC: "扫描身份证",
    takePhoto: "拍照",
    processing: "处理中...",
    icNumber: "身份证号码",
    fullName: "全名",
    next: "下一步",
    back: "返回",
    scanFace: "扫描人脸",
    recordVoice: "录制语音",
    startRecording: "开始录音",
    stopRecording: "停止录音",
    registerSuccess: "注册成功",
    faceMatchSuccess: "人脸匹配成功",
    faceMatchFailed: "人脸匹配失败",
    rescan: "重新扫描",
    voicePrompt: "请朗读：“我的名字是 {name}，我想注册。”",
    voiceRecorded: "语音录制成功",
    goToLogin: "前往登录",
    confirmation: "确认",
    enterIC: "输入身份证号码",
    check: "检查",
    notRegistered: "您尚未注册。请返回注册。",
    welcomeBack: "欢迎回来，{name}",
    selectMethod: "选择验证方式",
    faceAuth: "人脸验证",
    voiceAuth: "语音验证",
    loginVoicePrompt: "我的名字是 {name}，我想访问我的账户",
    loginSuccess: "登录成功",
    goHome: "前往主页",
    goMain: "前往主页面",
    signOut: "登出",
    pressToTalk: "按住说话，松开结束",
    listening: "正在聆听...",
    myKasih: "MyKasih / SARA",
    str: "STR",
    mainWelcome: "你好！今天有什么可以帮您的吗？",

    // Family Dock
    myFamily: "我的家人",
    noFamilyMembers: "尚未添加家庭成员。",
    pendingRequests: "待处理请求",
    wantsToAdd: "想添加您。",
    accept: "接受",
    reject: "拒绝",
    requestSent: "请求已发送",
    alreadySent: "请求已发送。",
    alreadyMember: "此用户已在您的家庭列表中。",
    
    // MyKasih Page
    myKasihBalance: "MyKasih 余额",
    saraBalance: "SARA 余额",
    expires: "到期",
    lastTransaction: "最近",
    payNow: "立即付款",
    payWithSara: "使用 SARA 付款",
    carriesForward: "结转（无有效期）",
    upcomingSara: "即将到来的 SARA 付款",
    nearbyMerchants: "附近的 MyKasih 商家",
    interactiveMap: "交互式地图视图",
    away: "距离",
    navigate: "导航",
    scanToPay: "扫码支付",
    scanInstruction: "向收银员出示此二维码以使用您的 MyKasih 余额。",
    limitNote: "最高交易限额：RM100",
    close: "关闭",
    
    // STR Page
    eligibleStr: "符合 STR 资格",
    applicationApproved: "您的申请已获批准。",
    upcomingPayments: "即将到来的付款",
    expected: "预计",
    recentPayment: "最近付款",
    date: "日期",
    notEligible: "不符合资格",
    notEligibleDesc: "您目前未注册或不符合 STR 资格。",
    nearestBsn: "最近的 BSN 分行",
    howToRegister: "如何注册",
    registerInstruction: "您可以通过官方 MySTR 门户网站注册 STR。",
    goToPortal: "前往 MySTR 门户",
    depositedStatus: "款项已存入您的账户",

    // AI Responses
    aiCheckStr: "您可以点击右侧按钮查看您的 STR 状态。",
    aiHelp: "我在这里为您提供帮助。按按钮询问有关 MyKasih 或 STR 的信息。",
    aiRegistered: "您已注册并登录。",
    aiDefault: "我听到您说：“{text}”。我能为您提供什么关于 MyKasih 或 STR 的帮助？",
  },
  'zh-tw': {
    appTitle: "我的網絡電子身份助手",
    registerTitle: "註冊新賬戶",
    registerDesc: "註冊新ID",
    loginTitle: "登錄",
    loginDesc: "訪問現有賬戶",
    scanIC: "掃描身份證",
    takePhoto: "拍照",
    processing: "處理中...",
    icNumber: "身份證號碼",
    fullName: "全名",
    next: "下一步",
    back: "返回",
    scanFace: "掃描人臉",
    recordVoice: "錄製語音",
    startRecording: "開始錄音",
    stopRecording: "停止錄音",
    registerSuccess: "註冊成功",
    faceMatchSuccess: "人臉匹配成功",
    faceMatchFailed: "人臉匹配失敗",
    rescan: "重新掃描",
    voicePrompt: "請朗讀：“我的名字是 {name}，我想註冊。”",
    voiceRecorded: "語音錄製成功",
    goToLogin: "前往登錄",
    confirmation: "確認",
    enterIC: "輸入身份證號碼",
    check: "檢查",
    notRegistered: "您尚未註冊。請返回註冊。",
    welcomeBack: "歡迎回來，{name}",
    selectMethod: "選擇驗證方式",
    faceAuth: "人臉驗證",
    voiceAuth: "語音驗證",
    loginVoicePrompt: "我的名字是 {name}，我想訪問我的賬戶",
    loginSuccess: "登錄成功",
    goHome: "前往主頁",
    goMain: "前往主頁面",
    signOut: "登出",
    pressToTalk: "按住說話，鬆開結束",
    listening: "正在聆聽...",
    myKasih: "MyKasih / SARA",
    str: "STR",
    mainWelcome: "你好！今天有什麼可以幫您的嗎？",

    // Family Dock
    myFamily: "我的家人",
    noFamilyMembers: "尚未添加家庭成員。",
    pendingRequests: "待處理請求",
    wantsToAdd: "想添加您。",
    accept: "接受",
    reject: "拒絕",
    requestSent: "請求已發送",
    alreadySent: "請求已發送。",
    alreadyMember: "此用戶已在您的家庭列表中。",
    
    // MyKasih Page
    myKasihBalance: "MyKasih 餘額",
    saraBalance: "SARA 餘額",
    expires: "到期",
    lastTransaction: "最近",
    payNow: "立即付款",
    payWithSara: "使用 SARA 付款",
    carriesForward: "結轉（無有效期）",
    upcomingSara: "即將到來的 SARA 付款",
    nearbyMerchants: "附近的 MyKasih 商家",
    interactiveMap: "交互式地圖視圖",
    away: "距離",
    navigate: "導航",
    scanToPay: "掃碼支付",
    scanInstruction: "向收銀員出示此二維碼以使用您的 MyKasih 餘額。",
    limitNote: "最高交易限額：RM100",
    close: "關閉",
    
    // STR Page
    eligibleStr: "符合 STR 資格",
    applicationApproved: "您的申請已獲批准。",
    upcomingPayments: "即將到來的付款",
    expected: "預計",
    recentPayment: "最近付款",
    date: "日期",
    notEligible: "不符合資格",
    notEligibleDesc: "您目前未註冊或不符合 STR 資格。",
    nearestBsn: "最近的 BSN 分行",
    howToRegister: "如何註冊",
    registerInstruction: "您可以通過官方 MySTR 門戶網站註冊 STR。",
    goToPortal: "前往 MySTR 門戶",
    depositedStatus: "款項已存入您的賬戶",

    // AI Responses
    aiCheckStr: "您可以點擊右側按鈕查看您的 STR 狀態。",
    aiHelp: "我在這裡為您提供幫助。按按鈕詢問有關 MyKasih 或 STR 的信息。",
    aiRegistered: "您已註冊並登錄。",
    aiDefault: "我聽到您說：“{text}”。我能為您提供什麼關於 MyKasih 或 STR 的幫助？",
  },
  ta: {
    appTitle: "எனது டிஜிட்டல் அடையாள உதவியாளர்",
    registerTitle: "புதிய கணக்கை பதிவு செய்யவும்",
    registerDesc: "புதிய அடையாளத்தை பதிவு செய்யவும்",
    loginTitle: "உள்நுழைய",
    loginDesc: "தற்போதைய கணக்கை அணுகவும்",
    scanIC: "IC ஸ்கேன்",
    takePhoto: "புகைப்படம் எடு",
    processing: "செயலாக்குகிறது...",
    icNumber: "IC எண்",
    fullName: "முழு பெயர்",
    next: "அடுத்தது",
    back: "பின்னால்",
    scanFace: "முகம் ஸ்கேன்",
    recordVoice: "குரல் பதிவு",
    startRecording: "பதிவைத் தொடங்கு",
    stopRecording: "பதிவை நிறுத்து",
    registerSuccess: "பதிவு வெற்றிகரமாக முடிந்தது",
    faceMatchSuccess: "முகம் வெற்றிகரமாக பொருந்தியது",
    faceMatchFailed: "முகம் பொருந்தவில்லை",
    rescan: "மீண்டும் ஸ்கேன் செய்",
    voicePrompt: "தயவுசெய்து படிக்கவும்: \"என் பெயர் {name} மற்றும் நான் பதிவு செய்ய விரும்புகிறேன்.\"",
    voiceRecorded: "குரல் வெற்றிகரமாக பதிவு செய்யப்பட்டது",
    goToLogin: "உள்நுழையச் செல்லவும்",
    confirmation: "உறுதிப்படுத்தல்",
    enterIC: "IC எண்ணை உள்ளிடவும்",
    check: "சரிபார்க்கவும்",
    notRegistered: "நீங்கள் பதிவு செய்யவில்லை. பதிவு செய்ய மீண்டும் செல்லவும்.",
    welcomeBack: "மீண்டும் வருக, {name}",
    selectMethod: "சரிபார்ப்பு முறையைத் தேர்ந்தெடுக்கவும்",
    faceAuth: "முகம் சரிபார்ப்பு",
    voiceAuth: "குரல் சரிபார்ப்பு",
    loginVoicePrompt: "என் பெயர் {name}, நான் எனது கணக்கை அணுக விரும்புகிறேன்",
    loginSuccess: "உள்நுழைவு வெற்றிகரமாக முடிந்தது",
    goHome: "முகப்புக்குச் செல்லவும்",
    goMain: "முக்கிய பக்கத்திற்குச் செல்லவும்",
    signOut: "வெளியேறு",
    pressToTalk: "பேச அழுத்தவும், நிறுத்த விடுவிக்கவும்",
    listening: "கேட்கிறது...",
    myKasih: "MyKasih / SARA",
    str: "STR",
    mainWelcome: "வணக்கம்! இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",

    // Family Dock
    myFamily: "என் குடும்பம்",
    noFamilyMembers: "குடும்ப உறுப்பினர்கள் இன்னும் சேர்க்கப்படவில்லை.",
    pendingRequests: "நிலுவையில் உள்ள கோரிக்கைகள்",
    wantsToAdd: "உங்களைச் சேர்க்க விரும்புகிறார்.",
    accept: "ஏற்றுக்கொள்",
    reject: "நிராகரி",
    requestSent: "கோரிக்கை அனுப்பப்பட்டது",
    alreadySent: "கோரிக்கை ஏற்கனவே அனுப்பப்பட்டது.",
    alreadyMember: "இந்த பயனர் ஏற்கனவே உங்கள் குடும்பப் பட்டியலில் உள்ளார்.",
    
    // MyKasih Page
    myKasihBalance: "MyKasih இருப்பு",
    saraBalance: "SARA இருப்பு",
    expires: "காலாவதியாகிறது",
    lastTransaction: "கடைசி",
    payNow: "இப்போது செலுத்துங்கள்",
    payWithSara: "SARA மூலம் செலுத்துங்கள்",
    carriesForward: "முன்னோக்கி கொண்டு செல்லப்படுகிறது (காலாவதி இல்லை)",
    upcomingSara: "வரவிருக்கும் SARA கட்டணம்",
    nearbyMerchants: "அருகிலுள்ள MyKasih வணிகர்கள்",
    interactiveMap: "ஊடாடும் வரைபடக் காட்சி",
    away: "தூரத்தில்",
    navigate: "செல்லவும்",
    scanToPay: "செலுத்த ஸ்கேன் செய்யவும்",
    scanInstruction: "உங்கள் MyKasih இருப்பைப் பயன்படுத்த இந்தக் QR குறியீட்டை காசாளரிடம் காட்டவும்.",
    limitNote: "அதிகபட்ச பரிவர்த்தனை வரம்பு: RM100",
    close: "மூடு",
    
    // STR Page
    eligibleStr: "STR க்கு தகுதியானது",
    applicationApproved: "உங்கள் விண்ணப்பம் அங்கீகரிக்கப்பட்டது.",
    upcomingPayments: "வரவிருக்கும் கொடுப்பனவுகள்",
    expected: "எதிர்பார்க்கப்படுகிறது",
    recentPayment: "சமீபத்திய கட்டணம்",
    date: "தேதி",
    notEligible: "தகுதியற்றவர்",
    notEligibleDesc: "நீங்கள் தற்போது பதிவு செய்யவில்லை அல்லது STR க்கு தகுதி பெறவில்லை.",
    nearestBsn: "அருகிலுள்ள BSN கிளைகள்",
    howToRegister: "பதிவு செய்வது எப்படி",
    registerInstruction: "அதிகாரப்பூர்வ MySTR போர்டல் மூலம் நீங்கள் STR க்கு பதிவு செய்யலாம்.",
    goToPortal: "MySTR போர்ட்டலுக்குச் செல்லவும்",
    depositedStatus: "உங்கள் கணக்கில் பணம் டெபாசிட் செய்யப்பட்டது",

    // AI Responses
    aiCheckStr: "வலதுபுறத்தில் உள்ள பொத்தானைக் கிளிக் செய்வதன் மூலம் உங்கள் STR நிலையைச் சரிபார்க்கலாம்.",
    aiHelp: "நான் உங்களுக்கு உதவ இங்கே இருக்கிறேன். MyKasih அல்லது STR பற்றி கேட்க பொத்தானை அழுத்தவும்.",
    aiRegistered: "நீங்கள் ஏற்கனவே பதிவு செய்து உள்நுழைந்துள்ளீர்கள்.",
    aiDefault: "நீங்கள் சொன்னதை நான் கேட்டேன்: \"{text}\". MyKasih அல்லது STR இல் நான் உங்களுக்கு எப்படி உதவ முடியும்?",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
